services:    # 컨테이너 정의(컨테이너의 집합체를 보주로 서비스라고 함)
  mysql:
    image: mysql:8.0  # 이미지 이름을 명시해서 지정 (Dockerfile이 없어도 실행 가능)
    container_name: springBasic
    environment:   # 환경 변수 설정
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: onboarding
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
  app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/onboarding
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8088:8080"